// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqxorgpuaglewqkdqijh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxeG9yZ3B1YWdsZXdxa2RxaWpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNjU5MDUsImV4cCI6MjA3NDc0MTkwNX0.ib_6s9JEen5NIlDFLfVf1GFOuvPRZ4m5cMVY2hYtqBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});